import { config } from "../config";

/**
 * Shared HTML shell for all outbound email. The disclaimer and unsubscribe
 * footer are hard-coded here — never generated by the model.
 */
export function emailLayout(bodyHtml: string, unsubscribeToken: string): string {
  const cfg = config();
  // Path-based token: query strings with "=" can be corrupted by
  // quoted-printable encoding in some email clients.
  const unsubUrl = `${cfg.APP_URL}/unsubscribe/${unsubscribeToken}`;
  return `<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background-color:#f6f5f1;">
  <div style="max-width:640px;margin:0 auto;padding:32px 20px;font-family:Georgia,'Times New Roman',serif;color:#1e222a;font-size:16px;line-height:1.65;">
    <div style="font-size:13px;letter-spacing:2px;text-transform:uppercase;color:#8a8578;margin-bottom:24px;">
      ${cfg.EMAIL_FROM_NAME}
    </div>
    ${bodyHtml}
    <hr style="border:none;border-top:1px solid #ddd8cc;margin:36px 0 16px;" />
    <div style="font-size:12px;color:#8a8578;line-height:1.6;">
      <p style="margin:0 0 8px;">
        This email is for informational and entertainment purposes only and is
        <strong>not investment advice</strong>, a recommendation, or an offer to buy or sell any
        security. The content is generated with the assistance of AI and may contain errors.
        Always do your own research and consider consulting a licensed financial adviser.
      </p>
      <p style="margin:0 0 8px;">
        Reply directly to this email to tell us how to improve your memos — your feedback shapes
        what you get tomorrow.
      </p>
      <p style="margin:0;">
        ${escapeHtml(cfg.POSTAL_ADDRESS)} ·
        <a href="${unsubUrl}" style="color:#8a8578;">Unsubscribe</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
